"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import show_create
from insta485.views.index import show_delete
from insta485.views.index import show_edit
from insta485.views.index import show_explore
from insta485.views.index import show_followers
from insta485.views.index import show_following
from insta485.views.index import show_login
from insta485.views.index import show_logout
from insta485.views.index import show_password
from insta485.views.index import show_post
from insta485.views.index import show_users
from insta485.views.index import show_images
from insta485.views.index import post_like
from insta485.views.index import post_comments
from insta485.views.index import post_accounts
from insta485.views.index import post_follow
from insta485.views.index import post_posts
from insta485.views.index import post_login
from insta485.views.index import post_edit
from insta485.views.index import post_delete
from insta485.views.index import post_upd_password
from insta485.views.index import post_create
